test 2

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -22,4 +22,23 @@ jobs:
               exit 1
           fi
               echo "Everything is good ! Keep on coding !"
-              exit 0
+              exit 
+
+compile:
+  runs-on: ubuntu-latest
+  steps:
+
+    - name: Checkout GH repository
+      uses: actions/checkout@master
+
+    - name: Compile repository
+      run: make
+
+    - name: Check binary presence
+      run: |
+        if [! -f ./swapupcase]; then
+          echo "Binary not found"
+          exit 1
+        fi
+        echo "Binary found"
+        exit 0
