test

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -14,12 +14,12 @@ jobs:
         run: cat coding-style-reports.log
       - name: Report banana result
         run: |
-        NB_ERROR=$(cat coding-style-reports.log | wc -l)
-        if [ $NB_ERROR -gt 0 ]; then
-            ERRORS=$(cat coding-style-reports.log);
-            echo "Banana found $NB_ERROR error(s)"
-            echo "$ERRORS"
-            exit 1
-        fi
-            echo "Everything is good ! Keep on coding !"
-            exit 0
+          NB_ERROR=$(cat coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+              ERRORS=$(cat coding-style-reports.log);
+              echo "Banana found $NB_ERROR error(s)"
+              echo "$ERRORS"
+              exit 1
+          fi
+              echo "Everything is good ! Keep on coding !"
+              exit 0
